# Generated by Django 3.2 on 2022-06-29 22:55

import datetime
import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FilmWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'created',
                    models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='date and time of creating'),
                ),
                (
                    'modified',
                    models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='date and time of modifying'),
                ),
                ('title', models.TextField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='creation date')),
                (
                    'rating',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name='rating',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[('movie', 'Фильм'), ('tv_show', 'ТВ-шоу')], max_length=15, verbose_name='type'
                    ),
                ),
            ],
            options={
                'verbose_name': 'filmwork',
                'verbose_name_plural': 'filmworks',
                'db_table': 'content"."film_work',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'created',
                    models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='date and time of creating'),
                ),
                (
                    'modified',
                    models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='date and time of modifying'),
                ),
                ('name', models.TextField(verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'db_table': 'content"."genre',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'created',
                    models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='date and time of creating'),
                ),
                (
                    'modified',
                    models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='date and time of modifying'),
                ),
                ('full_name', models.TextField(verbose_name='full name')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'db_table': 'content"."person',
            },
        ),
        migrations.CreateModel(
            name='PersonFilmWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'created',
                    models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='date and time of creating'),
                ),
                ('role', models.TextField(verbose_name='role')),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.person')),
            ],
            options={
                'db_table': 'content"."person_film_work',
                'unique_together': {('film_work', 'person')},
            },
        ),
        migrations.CreateModel(
            name='GenreFilmWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'created',
                    models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='date and time of creating'),
                ),
                (
                    'film_work',
                    models.ForeignKey(
                        db_index=False, on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork'
                    ),
                ),
                (
                    'genre',
                    models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='movies.genre'),
                ),
            ],
            options={
                'db_table': 'content"."genre_film_work',
            },
        ),
        migrations.AddField(
            model_name='filmwork',
            name='genre',
            field=models.ManyToManyField(through='movies.GenreFilmWork', to='movies.Genre'),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='person',
            field=models.ManyToManyField(through='movies.PersonFilmWork', to='movies.Person'),
        ),
        migrations.AddIndex(
            model_name='genrefilmwork',
            index=models.Index(fields=['film_work', 'genre'], name='genre_film__film_wo_399489_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='genrefilmwork',
            unique_together={('film_work', 'genre')},
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['creation_date'], name='film_work_creatio_02a6ad_idx'),
        ),
    ]
